language: go

go:
 - master

sudo: required

services:
  - docker

before_install:
  - docker build -t general_web_api .
  - docker run -d -p 127.0.0.1:80:80 --name general_web_api general_web_api

script:
  - docker ps | grep -q GeneralWebApi