language: go

go:
 - master

sudo: required

services:
  - docker

before_install:
  - docker build -t GeneralWebApi
  - docker run -d -p 127.0.0.1:80:80 --name GeneralWebApi GeneralWebApi

script:
  - docker ps | grep -q GeneralWebApi